services:
  redis:
    image: redis:7
    container_name: rinha-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  backend1:
    build: .
    container_name: backend-1
    depends_on:
      - redis
    environment:
      REDIS_URL: ${REDIS_URL}
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    
    ports:
      - "8003:8000"

    networks:
      - backend
      - payment-processor

  backend2:
    build: .
    container_name: backend-2
    depends_on:
      - redis
    environment:
        REDIS_URL: ${REDIS_URL}
        PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
        PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080

    ports:
      - "8004:8000"
    networks:
      - backend
      - payment-processor

  nginx:
    image: nginx:stable
    container_name: nginx-loadbalancer
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true